### ISSUE TITLE
Local credentials not updated in Download button

### ISSUE THREAD

**Issue by MeganerdNL** [Shard-Labs/docker-wireguard#24]
## Expected Behavior
In the details of a WireGuard VPN connection you can click the link _Show local credentials_. The three buttons  beneath change to  their _local_ version. When you click _Download local config_ you would expect that the local config is downloaded.

## Current Behavior
When you click _Download local config_ the **remote config** is downloaded.

## Steps to Reproduce
Do what I described.

## Environment
Debian 11
x86_64
**How docker service was installed:**
From the official docker repo,

**Comment by pablomendezroyo** [comment]
Thanks for the report! fixed by https://github.com/dappnode/DNP_DAPPMANAGER/commit/9a4c194b0e4fea487ac92509630cfca4a113c3e4
