### ISSUE TITLE
Add new endpoint to the API which returns modified config file

### ISSUE THREAD

**Issue by 3alpha** [Shard-Labs/docker-wireguard#9]
Since WIreguard configuration files can have only one Endpoint directive and that is an issue if a person is connecting from the local network with NAT loopback problems using public IP, it is convinient to have additional API endpoint which takes row with Enddpoint directive from configuration i.e.
```
Endpoint = xxxxx.dyndns.dappnode.io:51820
```
and changes it to 
```
Endpoint = LOCAL_IP:51820
```

**Comment by pablomendezroyo** [comment]
Having this feature implemented, what would happen if the user get the endpoint with the LOCAL_IP, and then eventually the user moves to another location out of the local network and tries to connect again?

**Comment by pablomendezroyo** [comment]
Would be possible to just serve two files at the same time to make things simple: one for remote and the other one for local

**Comment by 3alpha** [comment]
Yes and this is how we do it.
